// Preset configuration objects consumed by SynthEngine.
// Each preset describes oscillator setup, filter behaviour and envelope shape.
// cutoffScale narrows the CTRL2 filter range so each preset has its own character
// even before the player touches the knob.

export const PRESETS = [
  {
    code: '01',
    name: 'SINE',
    waveform: 'sine',
    oscCount: 1,
    detune: 0,
    osc2Ratio: 0,
    octaveShift: 0,
    cutoffScale: 1,
    attack: 0.03,
    decay: 0.1,
    sustain: 0.78,
    release: 0.3,
  },
  {
    code: '02',
    name: 'TRIANGLE',
    waveform: 'triangle',
    oscCount: 1,
    detune: 0,
    osc2Ratio: 0,
    octaveShift: 0,
    cutoffScale: 0.6,
    attack: 0.04,
    decay: 0.12,
    sustain: 0.72,
    release: 0.35,
  },
  {
    code: '03',
    name: 'SAW',
    waveform: 'sawtooth',
    oscCount: 1,
    detune: 0,
    osc2Ratio: 0,
    octaveShift: 0,
    cutoffScale: 0.85,
    attack: 0.01,
    decay: 0.08,
    sustain: 0.68,
    release: 0.25,
  },
  {
    code: '04',
    name: 'SQUARE',
    waveform: 'square',
    oscCount: 1,
    detune: 0,
    osc2Ratio: 0,
    octaveShift: 0,
    cutoffScale: 0.7,
    attack: 0.01,
    decay: 0.08,
    sustain: 0.62,
    release: 0.25,
  },
  {
    code: '05',
    name: 'DUAL SAW',
    waveform: 'sawtooth',
    oscCount: 2,
    detune: 14,
    osc2Ratio: 0.6,
    octaveShift: 0,
    cutoffScale: 0.85,
    attack: 0.015,
    decay: 0.1,
    sustain: 0.7,
    release: 0.3,
  },
  {
    code: '06',
    name: 'BASS',
    waveform: 'sawtooth',
    oscCount: 1,
    detune: 0,
    osc2Ratio: 0,
    octaveShift: -1,
    cutoffScale: 0.35,
    attack: 0.008,
    decay: 0.06,
    sustain: 0.82,
    release: 0.2,
  },
]
