// Starting patches. Each one configures VCO/VCF/LFO/ENV together, but every
// parameter remains fully editable afterwards — these are just presets,
// not separate synth engines.

export const PRESETS = [
  {
    code: '01',
    name: 'SINE',
    vco: { waveform: 'sine', dualSaw: false, pwmMod: 0, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.75, resonance: 0.1, lfoMod: 0, envMod: 0.15 },
    lfo: { waveform: 'sine', rate: 0.25, delay: 0 },
    envelope: { attack: 0.04, decay: 0.2, sustain: 0.8, release: 0.3 },
  },
  {
    code: '02',
    name: 'TRIANGLE',
    vco: { waveform: 'triangle', dualSaw: false, pwmMod: 0, detune: 0.5, pitchMod: 0.1 },
    vcf: { cutoff: 0.55, resonance: 0.15, lfoMod: 0.05, envMod: 0.2 },
    lfo: { waveform: 'sine', rate: 0.2, delay: 0.15 },
    envelope: { attack: 0.06, decay: 0.25, sustain: 0.72, release: 0.35 },
  },
  {
    code: '03',
    name: 'SAW',
    vco: { waveform: 'sawtooth', dualSaw: false, pwmMod: 0, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.65, resonance: 0.2, lfoMod: 0, envMod: 0.4 },
    lfo: { waveform: 'sine', rate: 0.3, delay: 0 },
    envelope: { attack: 0.01, decay: 0.15, sustain: 0.65, release: 0.25 },
  },
  {
    code: '04',
    name: 'SQUARE',
    vco: { waveform: 'square', dualSaw: false, pwmMod: 0.4, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.5, resonance: 0.25, lfoMod: 0, envMod: 0.35 },
    lfo: { waveform: 'sine', rate: 0.3, delay: 0 },
    envelope: { attack: 0.01, decay: 0.12, sustain: 0.6, release: 0.25 },
  },
  {
    code: '05',
    name: 'DUAL SAW',
    vco: { waveform: 'sawtooth', dualSaw: true, dualDetuneCents: 16, dualLevel: 0.65, pwmMod: 0, detune: 0.5, pitchMod: 0.05 },
    vcf: { cutoff: 0.6, resonance: 0.2, lfoMod: 0.1, envMod: 0.35 },
    lfo: { waveform: 'sine', rate: 0.25, delay: 0 },
    envelope: { attack: 0.015, decay: 0.18, sustain: 0.68, release: 0.3 },
  },
  {
    code: '06',
    name: 'BASS',
    vco: { waveform: 'sawtooth', dualSaw: false, pwmMod: 0, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.28, resonance: 0.3, lfoMod: 0, envMod: 0.55 },
    lfo: { waveform: 'sine', rate: 0.2, delay: 0 },
    envelope: { attack: 0.008, decay: 0.12, sustain: 0.8, release: 0.2 },
  },
  {
    code: '07',
    name: 'PLUCK',
    vco: { waveform: 'sawtooth', dualSaw: false, pwmMod: 0, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.5, resonance: 0.35, lfoMod: 0, envMod: 0.7 },
    lfo: { waveform: 'sine', rate: 0.3, delay: 0 },
    envelope: { attack: 0.002, decay: 0.12, sustain: 0.05, release: 0.15 },
  },
  {
    code: '08',
    name: 'PAD',
    vco: { waveform: 'sawtooth', dualSaw: true, dualDetuneCents: 20, dualLevel: 0.7, pwmMod: 0, detune: 0.5, pitchMod: 0.15 },
    vcf: { cutoff: 0.45, resonance: 0.15, lfoMod: 0.2, envMod: 0.25 },
    lfo: { waveform: 'sine', rate: 0.15, delay: 0.4 },
    envelope: { attack: 0.6, decay: 0.4, sustain: 0.75, release: 0.9 },
  },
  {
    code: '09',
    name: 'LEAD',
    vco: { waveform: 'sawtooth', dualSaw: false, pwmMod: 0, detune: 0.5, pitchMod: 0.05 },
    vcf: { cutoff: 0.72, resonance: 0.4, lfoMod: 0, envMod: 0.3 },
    lfo: { waveform: 'sine', rate: 0.35, delay: 0 },
    envelope: { attack: 0.005, decay: 0.1, sustain: 0.85, release: 0.2 },
  },
  {
    code: '10',
    name: 'BRASS',
    vco: { waveform: 'sawtooth', dualSaw: false, pwmMod: 0, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.4, resonance: 0.25, lfoMod: 0, envMod: 0.65 },
    lfo: { waveform: 'sine', rate: 0.2, delay: 0 },
    envelope: { attack: 0.09, decay: 0.15, sustain: 0.8, release: 0.25 },
  },
  {
    code: '11',
    name: 'ORGAN',
    vco: { waveform: 'square', dualSaw: false, pwmMod: 0.1, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.85, resonance: 0.05, lfoMod: 0, envMod: 0.05 },
    lfo: { waveform: 'sine', rate: 0.25, delay: 0 },
    envelope: { attack: 0.005, decay: 0.02, sustain: 0.95, release: 0.08 },
  },
  {
    code: '12',
    name: 'SUB',
    vco: { waveform: 'sine', dualSaw: false, pwmMod: 0, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.18, resonance: 0.05, lfoMod: 0, envMod: 0.1 },
    lfo: { waveform: 'sine', rate: 0.2, delay: 0 },
    envelope: { attack: 0.01, decay: 0.1, sustain: 0.9, release: 0.4 },
  },
  {
    code: '13',
    name: 'WOBBLE',
    vco: { waveform: 'sawtooth', dualSaw: false, pwmMod: 0, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.4, resonance: 0.45, lfoMod: 0.85, envMod: 0.2 },
    lfo: { waveform: 'sine', rate: 0.55, delay: 0 },
    envelope: { attack: 0.01, decay: 0.1, sustain: 0.9, release: 0.3 },
  },
  {
    code: '14',
    name: 'VIBRATO LEAD',
    vco: { waveform: 'triangle', dualSaw: false, pwmMod: 0, detune: 0.5, pitchMod: 0.55 },
    vcf: { cutoff: 0.6, resonance: 0.2, lfoMod: 0, envMod: 0.2 },
    lfo: { waveform: 'sine', rate: 0.4, delay: 0.25 },
    envelope: { attack: 0.03, decay: 0.15, sustain: 0.85, release: 0.3 },
  },
  {
    code: '15',
    name: 'FIFTHS',
    vco: { waveform: 'sawtooth', dualSaw: true, dualDetuneCents: 700, dualLevel: 0.7, pwmMod: 0, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.6, resonance: 0.15, lfoMod: 0, envMod: 0.3 },
    lfo: { waveform: 'sine', rate: 0.25, delay: 0 },
    envelope: { attack: 0.02, decay: 0.2, sustain: 0.75, release: 0.3 },
  },
  {
    code: '16',
    name: 'STAB',
    vco: { waveform: 'square', dualSaw: false, pwmMod: 0.2, detune: 0.5, pitchMod: 0 },
    vcf: { cutoff: 0.55, resonance: 0.4, lfoMod: 0, envMod: 0.5 },
    lfo: { waveform: 'sine', rate: 0.3, delay: 0 },
    envelope: { attack: 0.002, decay: 0.08, sustain: 0.1, release: 0.12 },
  },
]
